sovereign-nature/deep

apps/indexer/src/sovereign-nature-identifier.ts
=> Removed console.log from indexer

apps/explorer/components/SNIProperties.vue, apps/explorer/pages/details/[id].vue
- Make image dynamic
- Change the detail layout
=> Dynamic image

apps/explorer/components/SNIMap.vue, apps/explorer/package.json, yarn.lock
Implement library to convert WKT to GeoJSON
=> feature: Implement WKT to GeoJson

apps/explorer/components/SNIProperties.vue
Implement right format for Token URI and make url to ipfs work
=> refactor: Format key and link

apps/explorer-next/src/app/components/soul-filter/soul-filter.component.html
Change status numbers from 0 to 2
=> Refactor status list

apps/explorer-next/src/app/components/soul-detail/soul-detail.component.spec.ts, apps/explorer-next/src/app/components/soul-detail/soul-detail.component.ts, apps/explorer-next/src/app/components/soul-filter/soul-filter.component.html, apps/explorer-next/src/app/components/soul-filter/soul-filter.component.ts, apps/explorer-next/src/app/components/soul-properties/soul-properties.component.ts, apps/explorer-next/src/app/models/sni.ts, apps/explorer-next/src/app/models/soul.ts, apps/explorer-next/src/app/queries/sni.ts, apps/explorer-next/src/app/services/soul.service.spec.ts, apps/explorer-next/src/app/services/soul.service.ts
Refactor service with proper gql calls
=> Refactor soul service

apps/contracts/contracts/SovereignNatureIdentifier.sol, apps/contracts/contracts/abstracts/ComputeProvenance.sol, apps/contracts/contracts/abstracts/DataProvenance.sol, apps/contracts/contracts/interfaces/IComputeProvenance.sol, apps/contracts/test/SovereignNatureIdentifier.ts
Implementation of IComputeProvenance and IDataProvenance for Identifier contract.
=> Provenance interfaces implementation

apps/contracts/scripts/deploy.ts, apps/contracts/scripts/mint-lions.ts, apps/contracts/scripts/utils/index.ts, apps/indexer/src/utils.ts, apps/indexer/subgraph.yaml, packages/constants/index.ts, turbo.json
NFT Storage seems less reliable, so migrated to Pinata
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203930729817208
=> Using Pinata for metadata pinning

apps/explorer/src/app/components/soul-detail/soul-detail.component.ts, apps/explorer/src/app/components/soul-map/soul-map.component.html, apps/explorer/src/app/components/soul-map/soul-map.component.scss, apps/explorer/src/app/components/soul-map/soul-map.component.ts, apps/explorer/src/app/models/map-properties.ts
- Make map responsive
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203913825424379
=> refactor: Make map responsive

.vscode/settings.json, packages/clients/data.ts, packages/clients/link.ts, packages/clients/nft/index.ts, packages/clients/nft/queries/polkadot.ts, packages/clients/package.json, packages/clients/tests/integration.test.ts, packages/clients/tests/responses.ts, packages/clients/vite.config.ts, packages/constants/index.ts, pnpm-lock.yaml
@sni/clients package contains clients for common endpoints. The clients code is a minimal `axios` and `graphql-request` wrapper and expects error handling on the side of the application layer.
=> Added @sni/clients package

apps/verification-portal/src/lib/components/SimpleMap.svelte, apps/verification-portal/src/routes/assets/[assetAddress]/+page.svelte
- Added geoJson handling to the  map component
- replaced map tiles (see screenshot)
- enabled zoom feature as it's hard to understand positioning without it (needs testing with more data & zoom levels) 
here is also an alternative tile option that is uncommented now.
=> Map geoJson Layer & alternative tiles

apps/verification-portal/src/routes/assets/[assetAddress]/+page.server.ts, apps/verification-portal/src/routes/assets/[assetAddress]/+page.svelte
=> Asset link data & funds in dashboard

apps/verification-portal/src/lib/containers/LayoutLanding.svelte, apps/verification-portal/src/routes/+error.svelte, apps/verification-portal/src/routes/+page.svelte, apps/verification-portal/src/routes/assets/+error.svelte
=> Layout component

apps/verification-portal/src/app.postcss, apps/verification-portal/src/lib/components/Card.svelte, apps/verification-portal/src/lib/components/NFTImage.svelte, apps/verification-portal/src/lib/components/cards/CardFeatured.svelte, apps/verification-portal/src/lib/components/search/SearchResults.svelte, apps/verification-portal/src/lib/components/search/Web2SearchInput.svelte, apps/verification-portal/src/lib/components/search/Web3SearchInput.svelte, apps/verification-portal/src/lib/containers/FeaturedContainer.svelte, apps/verification-portal/src/lib/containers/SearchTabs.svelte, apps/verification-portal/src/lib/containers/Web2Featured.svelte, apps/verification-portal/src/lib/containers/Web2SearchContainer.svelte, apps/verification-portal/src/lib/containers/Web3Featured.svelte, apps/verification-portal/src/lib/data/Web3Featured.json, apps/verification-portal/src/lib/types.ts, apps/verification-portal/src/lib/utils.ts, apps/verification-portal/src/routes/assets/[assetAddress]/+page.server.ts
=> REA-23 Feature Cards

apps/verification-portal/src/lib/types.ts, apps/verification-portal/src/routes/assets/[assetAddress]/+page.server.ts, packages/clients/data.ts
Enclosed statistics fields into `statistics` field as subfields.
=> Updated data api

apps/verification-portal/package.json, apps/verification-portal/src/lib/components/web3/Web3Subscribe.svelte, apps/verification-portal/src/lib/web3Inbox.ts, apps/verification-portal/src/lib/web3Modal.ts, apps/verification-portal/src/routes/+layout.svelte, pnpm-lock.yaml
Suspected issues:
- Works only on an authorized domain?
- the[ signature config  ](https://docs.walletconnect.com/web3inbox/authorization-signatures/this-app) object is not correct
- other?
=> Added web3Inbox init & registration WIP

docs/real.md
=> Ale's first PR

apps/verification-portal/src/lib/components/web3/Web3ConnectBtn.svelte, apps/verification-portal/src/lib/config/web3Configs.ts, apps/verification-portal/src/lib/web3Modal.ts
- added network switch start view for connect wallet modal
- removed redundant code
- added dev/prod chain config
-
=> Added Network State tracking for WalletConnect modal

apps/verification-portal/src/app.postcss, apps/verification-portal/src/lib/components/RolloverBtn.svelte, apps/verification-portal/src/lib/components/navbar/DarkMode.svelte
=> Fixed colour issues and changed button action to goto

.vscode/settings.json, apps/assets-gateway/.gitignore, apps/assets-gateway/src/index.ts, packages/clients/nft/index.ts, packages/clients/tests/integration.test.ts, packages/clients/tests/responses.ts, turbo.json
OpenSea API access now supports multiple networks
=> Extended OpenSea API REA-71 

apps/verification-portal/src/lib/containers/SearchTabs.svelte
=> Mobile tab layout

apps/verification-portal/src/lib/components/RolloverBtn.svelte, apps/verification-portal/src/lib/components/web3/Web3Notifications.svelte, apps/verification-portal/src/lib/web3Inbox.ts
- Added loader to notification button
-  Added disabled state to Rollover button component
- Fixed undefined account flow
- Partial fix for REA-86 (needs double check) 
-  Fixed bug with account switch not re-registering and reloading inbox content
=> Added  state to indicate Inbox being Enabled

apps/verification-portal/src/lib/components/Toggle.svelte, apps/verification-portal/src/lib/components/web3/inboxModal/index.svelte, apps/verification-portal/src/lib/i18n/en/index.ts, apps/verification-portal/src/lib/i18n/i18n-types.ts, apps/verification-portal/src/lib/web3Inbox.ts
Unsubscribe button,
on toggle user gets option to save preferences 
On save preferences, the button displays the loading state till the Inbox watch detects updated preferences and rebuilds the types
=> Unsubscribe flow for Inbox Types

apps/verification-portal/src/lib/web3Inbox.ts
Made sure watchers trigger correct account data to be loaded
The problem now was that watchers were triggering for multiple accounts upon account switch.
Some watchers are account and some are Notify client based. 
Not all watchers have unsubscribe so a manual check for now to be refactored
=> Added checks for subscription watcher to be set only once,

apps/verification-portal/src/lib/components/carousel/Carousel.svelte
=> Check if more then one item for carousel controls

.vscode/settings.json, apps/claimer/.gitignore, apps/claimer/claimer.test.ts, apps/claimer/package.json, apps/claimer/src/claim.test.ts, apps/claimer/src/index.ts, apps/claimer/src/viem-validation.test.ts, apps/claimer/vitest.config.ts, apps/claimer/wrangler.toml, pnpm-lock.yaml
Initial architecture for the NFT claim service.
=> NFT Claimer initial architecture

apps/verification-portal/package.json, apps/verification-portal/src/lib/entities/InboxNotification/Notification.svelte, apps/verification-portal/src/lib/features/web3Inbox.ts, apps/verification-portal/src/lib/widgets/InboxModal/LayoutWrapper.svelte, apps/verification-portal/vite.config.ts, pnpm-lock.yaml
=> Web3 Inbox to version 1.0 migration

apps/verification-portal/src/lib/features/web3Modal.ts, apps/verification-portal/src/lib/widgets/ButtonWalletConnect/Web3ConnectBtn.svelte
- Removed network selector, modal is not a store
- Wallet state not preserved after refresh
=> Bug: Wallet-not-reopens for disconnection

apps/verification-portal/src/lib/components/search/Web2SearchInput.svelte, apps/verification-portal/src/lib/components/search/Web3SearchInput.svelte, apps/verification-portal/src/lib/components/web3/Web3AssetsContainer.svelte, apps/verification-portal/src/lib/containers/SearchTabs.svelte, apps/verification-portal/src/lib/containers/context/Web2Search.svelte, apps/verification-portal/src/lib/containers/context/Web3Connection.svelte, apps/verification-portal/src/lib/entities/FeaturedContainer.svelte, apps/verification-portal/src/lib/features/actions.ts, apps/verification-portal/src/lib/shared/collectionsConfig.ts, apps/verification-portal/src/lib/shared/i18n/custom-types.ts, apps/verification-portal/src/lib/shared/i18n/en/index.ts, apps/verification-portal/src/lib/shared/i18n/i18n-types.ts, apps/verification-portal/src/lib/types.ts, apps/verification-portal/src/routes/+page.ts, packages/address-utils/index.ts
Added tabs config file and unified the collectionAddress, key and other configs for web2/web3 & translations.
- fixed inconsistency in default active and hilights display
- fixed hilights api not unique value causing for-each bug
- removed axios use
```
export const collections: Collection[] = [
{
key: 'soundwaves',
collectionAddress: '0x6cc7c9b2aa5fdcc044f9a51d9d083fd16aeb0a78',
web3: { source: 'arbitrum', walletEnabled: true },
searchInput: {
searchEnabled: true,
inputMode: 'numeric',
},
},
{
key: 'wildsama',
collectionAddress: '0xdd0a0a15efc11930354b3e1eb1a62a87bf9abf30',
web3: { source: 'moonsama', walletEnabled: false },
searchInput: {
searchEnabled: false,
inputMode: 'numeric',
},
},
{
key: 'sub0',
collectionAddress: 'sub0',
web3: { source: 'polkadot', walletEnabled: false }, …
```
=> Collection Config file

apps/verification-portal/src/lib/containers/SearchTabs.svelte
=> Active tab reset back to default after soft navigation

.vscode/settings.json, apps/api/src/index.ts, apps/api/src/routes/assets.ts, apps/api/src/routes/wallets.ts
Currently, only works for Arbitrum network.
=> Wallet listing API

apps/verification-portal/src/lib/components/search/Web2SearchResults.svelte, apps/verification-portal/src/lib/shared/collectionsConfig.ts, apps/verification-portal/src/lib/widgets/CollectionTabs/CollectionTabs.svelte
The jump was caused by the content size shift (no scroll bar) caused by an outdated wait for the load of search data for highlight cards.
- Extra: removed the hardcoded HH prefix
=> Removed deprecated wait for web2data load logic

apps/verification-portal/src/app.postcss, apps/verification-portal/src/lib/components/Footer.svelte, apps/verification-portal/src/lib/components/NFTImage.svelte, apps/verification-portal/src/lib/components/carousel/NewsCarousel.svelte, apps/verification-portal/src/lib/entities/InboxNotification/Notification.svelte, apps/verification-portal/src/lib/shared/typography/CardHeader.svelte, apps/verification-portal/src/lib/shared/typography/Header.svelte, apps/verification-portal/src/lib/shared/typography/Property.svelte, apps/verification-portal/src/lib/shared/typography/Subheader.svelte, apps/verification-portal/src/lib/widgets/InboxModal/LayoutWrapper.svelte, apps/verification-portal/src/routes/assets/[assetAddress]/+page.svelte, apps/verification-portal/tailwind.config.cjs
- header/card spacing
- no background color mobile
- typography updates
=> Asset Page redesign, feedback and bugfixes

apps/verification-portal/src/lib/components/icons/LoginIcon.svelte, apps/verification-portal/src/lib/components/icons/PowerOnIcon.svelte, apps/verification-portal/src/lib/widgets/ButtonInboxConnect/Web3Notifications.svelte
=> Power on icon for shorter header feedback

apps/verification-portal/src/lib/components/icons/RefreshIcon.svelte, apps/verification-portal/src/lib/components/web3/Web3AssetsContainer.svelte, apps/verification-portal/src/lib/containers/context/Web3Connection.svelte, apps/verification-portal/src/lib/shared/i18n/en/index.ts, apps/verification-portal/src/lib/shared/i18n/i18n-types.ts
=> Refresh asset feed function

apps/verification-portal/src/lib/shared/collectionsConfig.ts, apps/verification-portal/src/lib/shared/i18n/en/index.ts, apps/verification-portal/src/lib/shared/i18n/i18n-types.ts, apps/verification-portal/src/lib/shared/siteConfigs.ts, apps/verification-portal/src/lib/widgets/CollectionTabs/CollectionTabs.svelte
@smakhtin please update the test collection configs as you see fit. Now collection configs have test flag. Typescript will warn if the the required translations for collection keys are missing.
=> Feature flag collectionTest

apps/verification-portal/src/lib/widgets/CollectionTabs/CollectionTabs.svelte
The previous feature flag included the test collection in index count so caused mismatch between tabs/tab nav
=> Fixed key/index mismatch bug for collection tabs

apps/api/src/routes/claims/index.ts, apps/api/src/routes/events/config.ts, apps/api/wrangler.toml, apps/verification-portal/src/lib/shared/i18n/i18n-types.ts
Protecting against double token claim
=> Double claim protection

apps/verification-portal/src/lib/components/NFTImage.svelte, apps/verification-portal/src/lib/shared/i18n/en/index.ts, apps/verification-portal/src/lib/shared/i18n/i18n-types.ts, apps/verification-portal/src/lib/widgets/MultipassCTA/MultipassCTA.svelte, apps/verification-portal/src/routes/assets/[assetAddress]/+page.svelte, packages/types/index.ts
-  variable naming consistency
- multipass type update
=> Multipass data from API,

apps/verification-portal/src/lib/widgets/NFTClaim/ClaimForm.svelte
Adjusted light mode text input:
=> Adjusted input text contrast in light mode

apps/verification-portal/src/lib/features/actions.ts
On test this took 4 calls to go from pending to claimed,
=> No-cache header claim call

apps/api/src/routes/claims/index.ts, apps/api/src/routes/claims/validators.test.ts, apps/api/src/routes/claims/validators.ts
Claimer now checks if address is EVM or Substrate compatible.
=> Claims address validation

apps/verification-portal/src/lib/entities/InboxNotification/MarkReadButton.svelte, apps/verification-portal/src/lib/entities/InboxNotification/Notification.svelte, apps/verification-portal/src/lib/features/web3Inbox.ts, apps/verification-portal/src/lib/features/web3InboxNotifications.ts, apps/verification-portal/src/lib/shared/components/CallbackBtn.svelte, apps/verification-portal/src/lib/widgets/ButtonInboxConnect/Web3Notifications.svelte, apps/verification-portal/src/lib/widgets/InboxModal/InboxModal.svelte, apps/verification-portal/src/lib/widgets/InboxNotificationList/NotificationList.svelte
Refactored notification code, replaced context with store logic.
-  marked all notifications as read feature
-  callback button component
=> Mark all notifications as read feature

apps/verification-portal/src/lib/features/web3InboxNotifications.ts, apps/verification-portal/src/lib/shared/i18n/en/index.ts, apps/verification-portal/src/lib/shared/i18n/i18n-types.ts, apps/verification-portal/src/lib/widgets/InboxNotificationList/NextPageBtn.svelte, apps/verification-portal/src/lib/widgets/InboxNotificationList/NotificationList.svelte
- Btn component
- Translation
- Reduced nr notifications per page to 10
=> Notification Next Page

apps/verification-portal/src/lib/features/web3Modal.ts
- added modal open state to modal connect btn
=> Replaced modal open/closed logic

apps/verification-portal/src/lib/entities/OgShare/CardBase.svelte, apps/verification-portal/src/lib/entities/OgShare/CardSquare.svelte
=> Added xs font size setting to share cards

.vscode/settings.json, apps/api/package.json, apps/api/src/index.ts, apps/api/src/routes/claims/index.ts, apps/api/src/routes/claims/schemas.ts, pnpm-lock.yaml
- OpenAPI spec generator
- Interactive docs
=> Added OpenAPI spec generator and docs generation via scalar

apps/verification-portal/src/lib/entities/featured/FeaturedCardSM.svelte, apps/verification-portal/src/lib/features/DOTphin.ts, apps/verification-portal/src/lib/features/MultipassStates.ts, apps/verification-portal/src/lib/shared/i18n/en/index.ts, apps/verification-portal/src/lib/shared/i18n/i18n-types.ts, apps/verification-portal/src/lib/shared/siteConfigs.ts, apps/verification-portal/src/lib/widgets/DOTphin/Header.svelte, apps/verification-portal/src/lib/widgets/DOTphin/Steps/CardEvolution.svelte, apps/verification-portal/src/lib/widgets/DOTphin/Steps/CardProof.svelte, apps/verification-portal/src/lib/widgets/DOTphin/Timeline.svelte, apps/verification-portal/src/lib/widgets/DOTphin/TimelineWrapper.svelte, apps/verification-portal/src/lib/widgets/MultipassCTA/MultipassCTA.svelte, apps/verification-portal/src/routes/+page.svelte
- Post collect manual proof count reduction  for pending state
- check if proofs are used/unused on claimProofTraitType
- translations
- reset multipass data on logged out state
- feature Dotphin config, added as hidden feature on main page
- udated DOTphin CTA block to handle hidden feature
- Added marketing links to site configs/cards
=> - Featured card link

apps/verification-portal/src/lib/shared/typography/CardHeader.svelte, apps/verification-portal/src/lib/widgets/NFTClaim/ClaimData.svelte, apps/verification-portal/src/lib/widgets/NFTClaim/NFTClaim.svelte
Seamless navigation post NFT Claim with new data-preload and in-app navigation.  Fixes delays caused by wallet re-initializing
=> Link target and data preload configuration to support internal header links

apps/verification-portal/src/lib/features/MultipassStates.ts, apps/verification-portal/src/lib/shared/i18n/en/index.ts, apps/verification-portal/src/lib/shared/i18n/i18n-types.ts, apps/verification-portal/src/lib/shared/multipassConfig.ts, apps/verification-portal/src/lib/shared/siteConfigs.ts, apps/verification-portal/src/lib/widgets/DOTphin/Steps/CardEvolution.svelte
- Evolution LIMITED state
- translations for LIMITED state
- evolution Feature flag
=> PRO0-303 Evolution Limit Configuration

apps/api/src/lib/shared/responses.ts, apps/api/src/lib/shared/types.ts, apps/api/src/middleware/session.ts, apps/api/src/routes/assets/assets.test.ts, apps/api/src/routes/assets/index.ts, apps/api/src/routes/claims/index.ts, apps/api/src/routes/claims/providers/crossmint.ts, apps/api/src/routes/dotphin/fixtures.ts, apps/api/src/routes/dotphin/index.ts, apps/api/src/routes/dotphin/lib.ts, apps/api/src/routes/events/index.ts, apps/api/src/routes/highlights/index.ts, apps/api/src/routes/siwe/index.ts, apps/api/src/routes/wallets/index.ts
Using new Hono context middleware functionality.
=> Api context refactoring
